Fix trying to get pointer to None in svm/linear.pyx (#5615)
This PR fixes the following bug in `svm/linear.pyx`:

After fitting `LinearSVC` and saving it using pickle, attempting to load and run `predict()` (or `decision_function()` and `predict_proba()` that call `__sync_model()`) results in the following error:
```
AttributeError                            Traceback (most recent call last)
----> 1 lin_svc_load.predict(X)

File .../lib/python3.10/site-packages/cuml/internals/api_decorators.py:188, in _make_decorator_function.<locals>.decorator_function.<locals>.decorator_closure.<locals>.wrapper(*args, **kwargs)
    185     set_api_output_dtype(output_dtype)
    187 if process_return:
--> 188     ret = func(*args, **kwargs)
    189 else:
    190     return func(*args, **kwargs)

File linear.pyx:693, in cuml.svm.linear.LinearSVM.predict()

File linear.pyx:667, in cuml.svm.linear.LinearSVM.__sync_model()

File linear.pyx:303, in cuml.svm.linear.LinearSVMWrapper.__cinit__()

AttributeError: 'NoneType' object has no attribute 'ptr'
```

I identified that the issue is caused by attempting to obtain a pointer to a variable with a None value in `LinearSVMWrapper.__cinit__()`. After fixing this and rebuilding, the code worked as expected.

Minimal code to reproduce the bug:
```python
import pickle
import numpy as np
from cuml.svm import LinearSVC

X = np.random.randn(10, 2)
y = np.random.randint(0, 2, 10)

svc = LinearSVC()
svc.fit(X, y)

with open("tmp.pkl", "wb") as f:
    pickle.dump(svc, f)
with open("tmp.pkl", "rb") as f:
    svc_load = pickle.load(f)

svc_load.predict(X)
```

If this is not the appropriate way to fix the issue, I would appreciate any corrections.

Authors:
  - yosider (https://github.com/yosider)
  - Simon Adorf (https://github.com/csadorf)
  - Dante Gama Dessavre (https://github.com/dantegd)

Approvers:
  - Simon Adorf (https://github.com/csadorf)

URL: https://github.com/rapidsai/cuml/pull/5615