Prevent undefined behavior when passing handle from Treelite to cuML FIL (#5849)
**Problem.** FIL unit tests have been failing when run with the pip wheel:
```
FAILED test_fil.py::test_fil_skl_classification[2-GradientBoostingClassifier-1-native-2-False-30-1000] - MemoryError: std::bad_alloc
FAILED test_fil.py::test_fil_skl_classification[2-GradientBoostingClassifier-1-native-2-True-30-1000] - MemoryError: std::bad_alloc
FAILED test_fil.py::test_fil_skl_classification[2-GradientBoostingClassifier-1-native-10-False-30-1000] - MemoryError: std::bad_alloc
FAILED test_fil.py::test_fil_skl_classification[2-GradientBoostingClassifier-1-native-10-True-30-1000] - MemoryError: std::bad_alloc
FAILED test_fil.py::test_fil_skl_classification[2-GradientBoostingClassifier-1-native-20-True-30-1000] - MemoryError: std::bad_alloc
FAILED test_fil.py::test_fil_skl_classification[2-GradientBoostingClassifier-10-native-2-False-30-1000] - MemoryError: std::bad_alloc
FAILED test_fil.py::test_fil_skl_classification[2-GradientBoostingClassifier-10-native-2-True-30-1000] - MemoryError: std::bad_alloc
FAILED test_fil.py::test_fil_skl_classification[2-GradientBoostingClassifier-10-native-10-False-30-1000] - MemoryError: std::bad_alloc
FAILED test_fil.py::test_fil_skl_classification[2-GradientBoostingClassifier-10-native-10-True-30-1000] - MemoryError: std::bad_alloc
FAILED test_fil.py::test_fil_skl_classification[2-GradientBoostingClassifier-10-native-20-True-30-1000] - MemoryError: std::bad_alloc
FAILED test_fil.py::test_fil_skl_classification[2-RandomForestClassifier-1-native-2-False-30-1000] - MemoryError: std::bad_alloc
```
In the meanwhile, the same tests were passing when run with the Conda package.

**Diagnosis**. When a Treelite model object is passed from the `treelite` Python package into the `cuml` Python package, `std::string` fields get corrupted. This is likely caused by C++ ABI incompatibilities, as different C++ compiler toolchain/version etc are used when building cuML pip wheel and Treelite pip wheel. More precisely, libtreelite in `cuml` is incompatible with libtreelite in `treelite`, and it's unsafe to directly pass a handle from one to another.

**Solution**. Have the `treelite` Python package export a serialized byte sequence, and have cuML re-construct the Treelite model from the bytes. [TL2cgen uses this technique to enable loose coupling between itself and Treelite](https://github.com/dmlc/tl2cgen/blob/082c02f8fe461ff86cd3602128055f0762d42195/python/tl2cgen/handle_class.py#L14-L32).

Authors:
  - Philip Hyunsu Cho (https://github.com/hcho3)

Approvers:
  - https://github.com/jakirkham
  - Dante Gama Dessavre (https://github.com/dantegd)
  - Bradley Dice (https://github.com/bdice)
  - Ray Douglass (https://github.com/raydouglass)

URL: https://github.com/rapidsai/cuml/pull/5849