Fix nightly CI: remove deprecated creation of columns by using explicit dtype (#5880)
After turning warnings as errors in pytests, the following error is blocking nightly (and I presume PR) CI: 

```python
================================================================================================================================================= short test summary info ==================================================================================================================================================
FAILED cuml/tests/test_array.py::test_get_set_item - FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.0' has dtype incompatible with int8, please explicitly cast to a compatible dtype first.
```

This PR fixes that by explicitly assigning columns with the correct type scalars.

Authors:
  - Dante Gama Dessavre (https://github.com/dantegd)

Approvers:
  - Divye Gala (https://github.com/divyegala)

URL: https://github.com/rapidsai/cuml/pull/5880