Small auto arima fixes (#3811)
Before this, running a call to autoarima.forecast would run into the following issue:

```bash
Traceback (most recent call last):
  File "bla2.py", line 17, in <module>
    model.search(s=12, d=1)
  File "/home/galahad/miniconda3/envs/cumlbench-019/lib/python3.8/site-packages/cuml/internals/api_decorators.py", line 360, in inner
    return func(*args, **kwargs)
  File "cuml/tsa/auto_arima.pyx", line 388, in cuml.tsa.auto_arima.AutoARIMA.search
AttributeError: 'CumlArray' object has no attribute 'reshape'
```

which was not caught since there is no forecast pytest for autoarima, only for arima

Authors:
  - Dante Gama Dessavre (https://github.com/dantegd)

Approvers:
  - Louis Sugy (https://github.com/Nyrio)
  - John Zedlewski (https://github.com/JohnZed)

URL: https://github.com/rapidsai/cuml/pull/3811